### ISSUE TITLE
Can't parse "set"

### ISSUE THREAD

**Issue by makuartur** [ppomes/myanon#14]
Can't parse set, like this:
CREATE TABLE `some_table` (
  `some_field` int NOT NULL AUTO_INCREMENT,
  `some_field` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `some_field` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `some_field` int NOT NULL,
  `some_field` int NOT NULL,
  `some_field` decimal(28,8) NOT NULL,
  `flags` **set**('vat_included') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `some_field` int NOT NULL,
fails with the error:
Dump parsing error at line 8: Unable to read table definition - Unexpected [s]
Could you fix it please?

**Comment by ppomes** [comment]
Hi,

Thanks for the report. I just added the parsing of 'set' type, can you pull the last code and try again?

Thanks!
Pierre
