### ISSUE TITLE
Fixed text truncated

### ISSUE THREAD

**Issue by Mat-Moo** [ppomes/myanon#16]
we have a rule
``key` = fixed '0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF'`
64 chars, going into a varchar(64) column, but the last character is being truncated, which then effects all our other data. If we try and extend this, we get an error as > 64 characters. Really love a fix :) or push of new code if you have any

**Comment by ppomes** [comment]
> we have a rule
> ``key` = fixed '0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF'`
> 64 chars, going into a varchar(64) column, but the last character is being truncated, which then effects all our other data. If we try and extend this, we get an error as > 64 characters. Really love a fix :) or push of new code if you have any

That should be simple, stay tuned! (I need a few days to find time)

**Comment by Mat-Moo** [comment]
Would be a life saver - ok maybe a tad OTT, but would really help me out of a pickle

**Comment by ppomes** [comment]
This should be fixed now, can you pull and try again? Thanks!

**Comment by Mat-Moo** [comment]
Ok, that works.... however we have some other fixed data types (going into varchars) which are longer than 64 :) So we use a key per user to encrypt other data, so things like an address become quite long. Is there any reason this couldn't just be 1026 (for 1024) max? Is there a memory constraint? I'm not up to speed with c, so not sure how this runs internally etc.

**Comment by ppomes** [comment]
Thanks for the feedback. There is no memory constraint, limits are arbitrary. Maybe you could upload a scenario (dump, config, and the result you would like) to see what I can fix? I am not sure to understand your issue (you can control each field length in the config file). I would be happy to help you!

**Comment by Mat-Moo** [comment]
```
tables = {
    `banks` = {
        `address` = fixed '53b5d7742e226ac82b347f885730f86135dd42622ad158855af509c6ffaed6d6c2ba76a4d1749da23f618f86ba921220'
    }
}

```
and that's a short one

**Comment by ppomes** [comment]
> ```
> tables = {
>     `banks` = {
>         `address` = fixed '53b5d7742e226ac82b347f885730f86135dd42622ad158855af509c6ffaed6d6c2ba76a4d1749da23f618f86ba921220'
>     }
> }
> ```
> 
> 
>     
>   
> 
> and that's a short one

Which limit do you need? 1024 (unquoted) is enough ?

**Comment by Mat-Moo** [comment]
I would imaging 1024 should be enough, but as the string is encrypted you can see that 64 chars isn't enough in this case :)

**Comment by ppomes** [comment]
I just added support for 1024 char, can you pull and try again? Thanks !
