### ISSUE TITLE
Randomise the seed

### ISSUE THREAD

**Issue by Mat-Moo** [ppomes/myanon#19]
After running this a few times, on different environments, I've noted that my first "texhhash" username is always the same random value - seems like need to add some randomisation onto the base?

**Comment by ppomes** [comment]
Yes, the hashing (hmac 256) is deterministic algorithm, it will produce the same hash for the same input/secret combination. In my case it was necessary to keep foreign key constraints. 

However, if you need pure random, I can add new option in the config file. Let me know!

**Comment by Mat-Moo** [comment]
Happy new year :) Im not sure it's an issue actually - I guess I was being naive and just thought it would be random random :)  I agree it's an enhancement as you have labeled it, don't think hard to implement, but your call :)

**Comment by ppomes** [comment]
Well not sure random will be very useful. I am closing this issue for now.
