### ISSUE TITLE
Support for --insert-ignore

### ISSUE THREAD

**Issue by check24-danielpaschsannapiu** [ppomes/myanon#23]
When using the mysqldump flag `--insert-ignore` myanon will not anonymize anything. 

Would be helpful to support it.

https://dev.mysql.com/doc/refman/8.0/en/mysqldump.html#option_mysqldump_insert-ignore

**Comment by ppomes** [comment]
Thanks for reporting this issue. It should work now, just pull the repo. Docker images (latest tag) are also updated.

Can you confirm it works as expected?

**Comment by ppomes** [comment]
some news @check24-danielpaschsannapiu ?

**Comment by check24-danielpaschsannapiu** [comment]
Yes! I tested it with compiled latest main branch. Works!

Thank you!
