### ISSUE TITLE
README - Additional support for MacOS 

### ISSUE THREAD

**Issue by jerome-h-dev** [ppomes/myanon#26]
## Request

Add additional support for MacOS users in README

- Add `m4` to `brew install` as OS version is incompatible.
- Add support for adding correct $PATH to `.zshrc` to point to homebrew installs and not OS versions.

## Reason
I found it difficult and time consuming getting this to build and test on my mac.

After adding the correct paths to the `.zshrc` and also using homebrew `m4` package I was able to build without issue.

Without these additions I was getting convoluted error messages which did not hint to a resolution.

**Comment by ppomes** [comment]
Hi!

Thanks for reporting this.

Can you share the error you had with macOS m4? I have several Mac (Intel and M1), I did not have any build issue on last three macOS major releases. 

Thanks!
Piere

**Comment by ppomes** [comment]
Oops sorry, brew m4 seems to be a dependency of brew automake/autoconf.

you are right it will be easier to install it manually and have the correct PATH.
