### ISSUE TITLE
Issues on JSON fields with backslashes and double quotes

### ISSUE THREAD

**Issue by SpartakusMd** [ppomes/myanon#29]
I'm using version 8.0 of MySQL. I found two edge cases when handling JSON fields and both produce invalid MySQL dump files. I can split the issue in 2 if it will be easier to handle.

### Backslashes in the JSON field are stripped
Table 11.1  from https://dev.mysql.com/doc/refman/8.4/en/string-literals.html contains all the characters which should have a backslash in front of them.

**Initial data**
```sql
INSERT INTO `anontest` VALUES (1,'{\"name\":\"John Doe\",\"title\": \"It\'s time for \\fun\\!\"}');
```

**Output**
```sql
INSERT INTO `anontest` VALUES (1,'{\"name\":\"joswz\",\"title\":\"It's time for fun!\"}');
```

### Double quotes in the JSON value produce error

> WARNING! Table/field `anontest`:`metadata`: Unable to parse json field, skip anonymization
> WARNING! Field `anontest`:`metadata` - JQ filter '.name' from config file has not been found in dump. Maybe a config file error?

**Initial data**
```sql
INSERT INTO `anontest` VALUES (1,'{\"name\": \"John Doe\", \"title\": \"It is time for \\\"fun\\\"!\"}');
```

**Output**
As a result the JSON value is left intact, but it has two single quotes at beginning and the end of the value.
```sql
INSERT INTO `anontest` VALUES (1,''{\"name\": \"John Doe\", \"title\": \"It is time for \\\"fun\\\"!\"}'');
```

**Database Table**
```sql
CREATE TABLE `anontest` (
  `id` int NOT NULL AUTO_INCREMENT,
  `metadata` json DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```

**myanon.conf**
```
tables = {
   `anontest` = {
      `metadata` = json {
        path 'name' = texthash 5
      }
   }
}
```

**mysqldump**
[full-dump.sql.zip](https://github.com/user-attachments/files/16398368/full-dump.sql.zip)

**Comment by ppomes** [comment]
Hi!

Thanks for reporting this. I just committed a draft in branch issue29. It is a draft because I need to handle all characters you mentioned from docs.

However, the code in branch is working with your dump file (a valid dump file is produced).

Can you confirm this is you are expecting?

Thanks,
Pierre

**Comment by SpartakusMd** [comment]
I have tested it for and found it cannot parse values where there is a newline `\n` as it's encoded to `\\n`.

Example of line:

```sql
INSERT INTO `anontest` VALUES (4,'{\"name\":\"Aiden\",\"title\":\"Multiline\\nmessage test.\"}');
```

**Comment by ppomes** [comment]
Hi!

Sorry the long delay. Can you try again? I updated the test case with your current data, it should work now.

Thanks!
Pierre

**Comment by SpartakusMd** [comment]
Hello Pierre. Yes now it works.

There are still edge cases (which probably won't happen in real life), for example if there are backslashes at the end of the value. It's not a issue and can be fixed whenever it's discovered. However, there is a problem when the parsing fails, in the anonymized version around the values extra quotes are added which renders the resulting file invalid. Could this also be addressed?

Also, if possible, when logging a warning, maybe add the line number where the issue happened so it's easier to debug? I can open a separate issue for it.

**Input**
```sql
INSERT INTO `anontest` VALUES (5,'{\"name\": \"Aiden\", \"title\": \"Backslashes at the end\\\"}');
```

**Output**
```sql
INSERT INTO `anontest` VALUES (5,''{\"name\": \"Aiden\", \"title\": \"Backslashes at the end\\\"}'');
```

**Error**
> WARNING! Table/field `anontest`:`metadata`: Unable to parse json field, skip anonimyzation
> WARNING! Field `anontest`:`metadata` - JQ filter '.name' from config file has not been found in dump. Maybe a config file error?

**Comment by ppomes** [comment]
Hi! 

First of all, I added line number and buffer parsed when json parsing fails.

From your last comment, the input provided (3 backslashes) is not valid when pushed on a real mysql server (I suspect you tried to forge it by hand):
- from json side, a backslash should be escaped (=> 2 backslash)
- when reading from stdin in SQL, each backslash should be escaped (=> then 4 backslash and not three).

Screenshot:
```
ppomes@imac27:~$ cat pp.txt
REPLACE INTO `anontest` VALUES (5,'{\"name\": \"Aiden\", \"title\": \"Backslashes at the end\\\\"}');

ppomes@imac27:~$ cat pp.txt | sudo mysql issue29

ppomes@imac27:~$ sudo mysql issue29
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 100
Server version: 8.0.39-0ubuntu0.24.04.1 (Ubuntu)

Copyright (c) 2000, 2024, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> select * from anontest where id=5 ;
+----+--------------------------------------------------------+
| id | metadata                                               |
+----+--------------------------------------------------------+
|  5 | {"name": "Aiden", "title": "Backslashes at the end\\"} |
+----+--------------------------------------------------------+
1 row in set (0.00 sec)
```

I improved code, I updated test case, it should now work (with 4 backslashes)

Let me know!
Pierre

**Comment by ppomes** [comment]
I also fixed the code when json parsing fails: now the original json field will be used as output.

**Comment by SpartakusMd** [comment]
Tested. Works like a charm.

But for some reason line number is not correct. Tested by intentionally making invalid SQL in the insert (for example, remove a comma). Error line in file is `38` but the message shows `5`. It's not a critical functionality.

> Dump parsing error at line 5: syntax error - Unexpected [(]

**Comment by ppomes** [comment]
Hi!

Good news ;-) I just merged the branch as is.

I will create a new ssue for the wrong line number

Thank,
Pierre

**Comment by ppomes** [comment]
Merged

**Comment by SpartakusMd** [comment]
Thank you for all the effort!
