### ISSUE TITLE
NULL values are not maintained for rows with both NULL and non-NULL values

### ISSUE THREAD

**Issue by ccozzolino** [ppomes/myanon#3]
When anonymizing a column that contains both NULL and non-NULL values the NULL values are hashed. I would expect only the non-null values to be hashed and the NULL rows to maintain their current NULL value.

I've attached a tar.gz with an example:
- **null-example.conf** = the myanon config
- **null-example-mysqldump.sql** = the mysqldump of the database I'm using as an example
- **null-example-anonymized.sql** = the myanon result after anonymizing null-example-mysqldump.sql

On line 48 of n**ull-example-anonymized.sql** you can see that rows 3 & 5 hash the NULL value to 'ahavykafkojauwmdriqpohobuuttmiif'.  I would expect those values to remain NULL.
[null-example.tar.gz](https://github.com/ppomes/myanon/files/8476950/null-example.tar.gz)

**Comment by ppomes** [comment]
Thanks for the report, I will have a look in the next few days. I will let you know.

**Comment by ppomes** [comment]
you are right, I just pushed a fix to keep NULL values.

**Comment by ccozzolino** [comment]
Thanks for the quick turnaround.  At initial glance it appears that the fix is working; however, when I run the latest changes in main against my real data I see columns getting anonymized that I haven't specified in my config.  Not sure if it makes a difference but I've been building from the v0.3 tag originally.  When I revert to that branch and process my real data the proper columns are anonymized.  The only difference I see between v0.3 and main is your fix so I'm curious if it broke something else.  I'll try to provide an example when I get a chance.

**Comment by ppomes** [comment]
I think your description is enough, and yes commit 1fafb238ddd71d044137482bd47a1998c6fe75d4 was buggy. I fixed it (a counter pointing to current field in table was not updated on NULL values, leading to field mismatch...). Please note I fixed it using the same commit ref (git squash). I hope it will work now, let me know!

**Comment by ccozzolino** [comment]
Thanks again for the quick response.  I've confirmed that the latest main handles the mixed NULL case properly and is anonymizing the correct columns.  Closing issue.

**Comment by ccozzolino** [comment]
I've found a different scenario related to this original issue.  If the first value of a mixed NULL column is NULL, then anonymization is skipped for all subsequent values of that column.  

I've attached a tar.gz with an example:

    null-example.conf = the myanon config
    null-example-mysqldump.sql = the mysqldump of the database I'm using as an example
    null-example-anonymized.sql = the myanon result after anonymizing null-example-mysqldump.sql

On line 48 of **null-example-anonymized.sql** you can see that all subsequent values of `colB` are not anonymized.  If you change `(1,NULL,'v1c')` to `(1,'v1b','v1c')` and change one or more `colB` values to NULL the mixed NULL anonymization works as expected.

[null-example.tar.gz](https://github.com/ppomes/myanon/files/8662294/null-example.tar.gz)

**Comment by ppomes** [comment]
Thanks for the report, I will have a look ASAP.

**Comment by ppomes** [comment]
Ok, issue found, last code from main branch should be ok! Can you confirm?
