### ISSUE TITLE
Problem myanon

### ISSUE THREAD

**Issue by thandrade830** [ppomes/myanon#34]
Hey friend,
Can you help me?
I'm using your program in my dump.
But I'm getting this error:
```
*** stack smashing detected ***: terminated
Aborted (core dumped)
```
Observation: i am using several faker functions in Python.
I will be very grateful if you help me.
Thanks!

**Comment by ppomes** [comment]
Hi ! 

Can you provide me a complete scenario causing the crash?  (dump file and config file)

I would be more than happy to help you. 

Regards,
Pierre

**Comment by ppomes** [comment]
Any news @thandrade830 ?
