### ISSUE TITLE
Feature request ability to use faker to generate more robust data

### ISSUE THREAD

**Issue by rsaylor73** [ppomes/myanon#5]
The process now that generates random hash data works but it would be useful if we could pipe to a faker data generator to be able to take the production data and replace with test data that is human readable.

https://github.com/joke2k/faker

**Comment by ppomes** [comment]
Hi @rsaylor73, 

Sorry for the so looooong delay.... Just to let you know, I started to work on this request.

Pierre

**Comment by ppomes** [comment]
Nope :-( Finally did not have any time to do it.... :-(

**Comment by ppomes** [comment]
@rsaylor73, @alexliam83 , @davidmr163,

I just added some code as a draft, to provide python support. Python faker can now  be used.

You need to install python libraries (for Ubuntu: apt-get install python3-dev)

Then, you need to build from branch issue5:
```
git checkout issue5
git pull
./autogen.sh
./configure --enable-python
make
make check
```

For the faker example :
```
PYTHONPATH=$(pwd)/tests main/myanon -f tests/faker_test.conf < tests/faker_test.sql
```

Key points are:
- a python script is given in the global section of the config file (without .py extension)
- the path of this script must be set by the env variable PYTHONPATH
- this script must contain all the function you need (ie : faker function for names, faker function for emails, etc...)
- for each field, you can select which faker function you want to use

Doc is not yet updated. 

Feedback needed! If this new feature seems ok for you, I will do more tests/improvements, I will update the doc and merge into main branch.

Thanks!
Pierre

**Comment by SpartakusMd** [comment]
I was also looking for a solution which could anonymize backups. From the start this was one of my best choises, the downside was the random strings that would get used which kept me from using it. Giving the possibility to run any python code to get the value of a string is excellent solution.

I did run a couple of tests myself, and it works. One thing I would also like (may be added later), is to send the value to be replaced to the python script. This would allow to have custom logic based on the current value. I will await a release before using it, hopefully soon.

Thank you Pierre for your work on this tool.

**Comment by ppomes** [comment]
Hi @SpartakusMd,

Thanks for your feedback! I agree with you, sending the value to the python script is a good thing.

I just added it, still in branch issue5, and as a basic example in tests/test_python.py , the python script just reverses the string.

Can you try it to confirm that it works as you would like? 

Thanks,
Pierre

**Comment by SpartakusMd** [comment]
Checked the update. Currently the script creates an invalid SQL. For the values converted, it adds two timis the single quote before and after the value. It is even present in the test.

**Expected**:
```
INSERT INTO `players` VALUES (10,'regoR'),(20,'leafaR'),(30,'kavoN'),(40,'ydnA');
```

**Result**:
```
INSERT INTO `players` VALUES (10,''regoR''),(20,''leafaR''),(30,''kavoN''),(40,''ydnA'');
```

**Comment by ppomes** [comment]
Thanks for this, this should now be fixed. 

There was an issue since day one, anonymization function did not remove (beginning and ending) quotes for string coming from db's. Since the output as a logic to add quotes for quoted types, double quotes were inserted.

Thanks!
Pierre

**Comment by SpartakusMd** [comment]
Looks good. Thank you for the great job. When do you plan on tagging a new version?

**Comment by ppomes** [comment]
Your feedback motivates me to do it current month ;-) 

I will integrate the branch into main.

**Comment by SpartakusMd** [comment]
Hey Pierre, I forgot to ask one thing.

If I want to build a version with Python, it's not possible to build a static version anymore with `make LDFLAGS="-static"`, right? I changed the `./configure --enable-python` in the Dockerfile and it fails. There are a lot of undefined references and it stops with `collect2: error: ld returned 1 exit status`.

It's not an issue, just wanted to make sure that it's not possible.

Thanks,
Marin

**Comment by ppomes** [comment]
Hi Martin,

Yes it is normal since (afaik) standard distributions do not provide a static library (.a) for libpython.

However, I was able to build a docker image with dynamic libs, using something like:
```
FROM alpine:latest as builder
RUN apk update && apk add --no-cache \
    build-base \
    flex \
    bison \
    autoconf \
    automake \
    libtool \
    python3-dev
WORKDIR /app
COPY . .
RUN ./autogen.sh && \
    ./configure --enable-python && \
    make

FROM alpine:latest
COPY --from=builder /app/main/myanon /bin/myanon
RUN apk update && apk add --no-cache \
    python3
CMD ["/bin/sh"]
```
And then: 

`docker run -it --rm -v ${PWD}:/app -e PYTHONPATH=/app/tests myanon  sh -c '/bin/myanon -f /app/tests/test_python.conf < /app/tests/test_python.sql'`

The image size jumps from 6M to 50M, but I think there is no other (simple) solution.

If this is working for you I will update the Dockerfile.

Pierre

**Comment by ppomes** [comment]
It is working for the "test_python" scenario, because this scenario does not need any package. However, things become complicated when packages are needed (I am not a docker expert).

**Comment by SpartakusMd** [comment]
Cool, got it working. Works as a charm now.
Thank you Pierre

**Comment by ppomes** [comment]
New Dockerfile commited! With 2 add-ons :
- py3-faker (apk): python scripts based on faker will run out of the box,
- pip: may be used to install packages before running myanon. 

Faker test from main branch:

`docker run -it --rm -v ${PWD}:/app -e PYTHONPATH=/app/tests myanon  sh -c '/bin/myanon -f /app/tests/faker_test.conf < /app/tests/faker_test.sql'`
