### ISSUE TITLE
Generate fields with data other fields

### ISSUE THREAD

**Issue by crummy** [ppomes/myanon#6]
Given a field like `id` and a field like `username`, I'd like to keep `id` the same but set `username` to `user<id>`.

I imagine something like:

```
tables = {
   `people` = {
     `id`   = texthash 10
     `username` = sql CONCAT('user', id);
   }
}
```

Consider this a feature request. Thanks :)

**Comment by ppomes** [comment]
Assuming the original table contains:
INSERT into table values(1,"Roger");
INSERT into table values(2,"Rafael");
INSERT into table values(2,"Novak");

you would like to have:
INSERT into table values(1,"user1");
INSERT into table values(2,"user2");
INSERT into table values(2,"user3");

Is it right?

**Comment by crummy** [comment]
That's exactly what I'm looking for, yes.

**Comment by Mat-Moo** [comment]
This would be SOOOOO useful!

**Comment by ppomes** [comment]
> This would be SOOOOO useful!

Il will try, I need free time;-)

**Comment by ppomes** [comment]
Ok, I will try to do what you really need!

**Comment by ppomes** [comment]
Hi,

I have a draft! I pushed the code into the "issue6" branch, with a test case "concat" to illustrate. I think you can have a look into the test case, it is self explained.

Maybe you can try this fix? 

This is draft, and there is a limitation: the key field must be before the anonymized field. But otherwise, it should work;-)

Please let me know,
Pierre

**Comment by Mat-Moo** [comment]
so we use `key` in config to mark the row we want to be what will be concatenated,  then `concatkey` to have it mixed together.  Clean and easy concept, might be good to have append-key and prepend-key instead, so you can have start or end? row-1 and 1-row depending on preference? Will see if I can test

**Comment by ppomes** [comment]
Very good idea append-key / prepend-key! Maybe with an optional char as separator.

**Comment by ppomes** [comment]
I modified the initial draft with appendkey/prependkey! Much better thanks for the idea ;-)

**Comment by ppomes** [comment]
Hi @crummy , did you have any opportunity to test the draft?

**Comment by crummy** [comment]
Sorry it took me so long to test this! I tested two cases:

```
tables = {
   `user` = {
     `id`   = key
     `username`   = appendkey 'user'
   }
}
```
This first one worked fine. I ended up with inserts like:
```
INSERT INTO `user` VALUES (1, 'user1', ...
```
However, I tried it with a different "key" and it didn't work as well:
```
tables = {
   `user` = {
     `personid`   = key
     `username`   = appendkey 'user'
   }
}
```
Here I ended up with inserts with just the word `user`, like:
```
INSERT INTO `user` VALUES (1, 'user', ...
```

**Comment by ppomes** [comment]
Ok, can you give me the dump file for the second test case? Thanks!

**Comment by crummy** [comment]
The dump file is very large, do you need the whole thing? I could look into cutting it down but it might take a while. Here is the `user` table:
```
create table mycompany.user
(
    id                     int auto_increment
        primary key,
    username               varchar(255)                           not null,
    email                  varchar(255)                           null,
    enabled                tinyint(1)                             not null,
    salt                   varchar(255)                           not null,
    password               varchar(255)                           not null,
    last_login             datetime                               null,
    locked                 tinyint(1)                             not null,
    expired                tinyint(1)                             not null,
    expires_at             datetime                               null,
    confirmation_token     varchar(255)                           null,
    password_requested_at  datetime                               null,
    roles                  longtext                               not null comment '(DC2Type:array)',
    personid               int                                    null,
    storagekey             varchar(255)                           null,
    secrethash             varchar(255)                           not null,
    points                 int                                    null,
    freshchat_restore_id   varchar(255)                           null,
    show_rate              tinyint(1) default 0                   null,
    updated_at             timestamp  default current_timestamp() not null on update current_timestamp(),
    created_at             timestamp  default current_timestamp() not null,
    constraint email_UNIQUE
        unique (email),
    constraint studentid
        unique (personid),
    constraint username_UNIQUE
        unique (username)
)
    charset = utf8mb4;

create index secrethash
    on mycompany.user (secrethash);
```

**Comment by ppomes** [comment]
Ok, understood. That's the limitation I was talking above on [December 20th](https://github.com/ppomes/myanon/issues/6#issuecomment-1358727241), the key field must be before the field to anonymize. That explains why your first test is ok. So more work is needed if you need this.

**Comment by crummy** [comment]
Ah I see - that's fine I don't mind reorganising my columns. In that case this does just what I need, thank you.

**Comment by ppomes** [comment]
For now, I will add a warning in case of the key is after the field to anonymize, update the doc, and merge into main. This limitation could be a future enhancement.

**Comment by ppomes** [comment]
Merged in main branch
